export default {
  wallet: {
    balance: Math.round(Math.random() * 100 + 200),
    blocks: {},
    transactions: [
      {
        name: 'Sintel 2048',
        value: 3.25,
        date: '2018-05-23T18:25:43.511Z',
      },
      {
        name: 'Pioneer One: Episode 1',
        value: 4,
        date: '2018-05-21T13:33:43.511Z',
      },
      {
        name: 'Metropolis',
        value: 2.5,
        date: '2018-05-18T20:14:43.511Z',
      },
    ],
    fetchingTransactions: false,
    receiveAddress: null,
    gettingNewAddress: false,
    draftTransaction: {},
    sendingSupport: false,
  },
  // user: {
  //   authenticationIsPending: false,
  //   userIsPending: false,
  //   emailNewIsPending: false,
  //   emailNewErrorMessage: '',
  //   emailToVerify: '',
  //   inviteNewErrorMessage: '',
  //   inviteNewIsPending: false,
  //   inviteStatusIsPending: false,
  //   invitesRemaining: 0,
  //   invitees: [],
  //   user: {
  //     id: 609187,
  //     language: 'en',
  //     given_name: null,
  //     family_name: null,
  //     created_at: '2018-01-27T16:49:36Z',
  //     updated_at: '2018-01-27T16:49:36Z',
  //     is_token_confirmed: true,
  //     invited_by_id: null,
  //     invited_at: null,
  //     invites_remaining: 0,
  //     invite_reward_claimed: false,
  //     phone_number: null,
  //     country_code: null,
  //     primary_email: null,
  //     has_verified_email: false,
  //     is_identity_verified: false,
  //     is_reward_approved: false,
  //   },
  // },
};
